databaseType = "PostgreSql"
id = "ec047de1-f9e8-46ee-9206-124f9e5d4ea7"
name = "dbRosetta"

[environments.ci]
password = "${CI_DATABASE_PASSWORD}"
schemas = [ "dbrosetta" ]
url = "${CI_DATABASE_URL}"
user = "${CI_DATABASE_USER}"

[environments.default]
url = "jdbc:postgresql://rosettacluster.postgres.database.azure.com:5432/dbrosetta?sslmode=require"
user = "postgres"
password = "${FLYWAY_PASSWORD}"
schemas = [ "dbrosetta" ]

[environments.development]
password = "${FLYWAY_PASSWORD}"
schemas = [ "dbrosetta" ]
url = "jdbc:postgresql://rosettacluster.postgres.database.azure.com:5432/dbrosetta?sslmode=require"
user = "postgres"

[environments.shadow]
password = "${FLYWAY_PASSWORD}"
schemas = [ "dbrosetta" ]
url = "jdbc:postgresql://rosettacluster.postgres.database.azure.com:5432/dbrosetta_shadow?sslmode=require"
user = "postgres"

[flyway]
baselineDescription = "Initial baseline from existing schema"
baselineOnMigrate = false
baselineVersion = "1"
callbackLocations = [ "filesystem:callbacks" ]
cleanDisabled = true
encoding = "UTF-8"
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
table = "flyway_schema_history"
validateMigrationNaming = true

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
showDeploymentDecision = false
enableMigrations = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"
